### PR TITLE
Installing json-server v0.1.0/install

### PR DESCRIPTION
**Pull request by CoffeerLatte**
- [x] Adding README.md
- [x] Created .gitignore
- [x] Created db.json

### CODE REVIEW

**Comment by parc02** [comment]
LGTM

**Review by parc02 — APPROVED** [review]
LGTM

**Review by ldh0308 — APPROVED** [review]
LGTM

**Review by shimguh — APPROVED** [review]

**Review by dhkdtld37 — APPROVED** [review]
image

**Pull request merged**
